name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 2: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to ensure latest version
          pip install -r requirements.txt     # Install all dependencies listed in requirements.txt

      # Optional: Run Tests
      - name: Run Tests
        run: |
          pip install pytest
          export PYTHONPATH=$PYTHONPATH:./src  # Ensure the 'src' directory is part of the PYTHONPATH
          pytest tests

      # Optional: Lint with flake8
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 src

      # Optional: Format check with black
      - name: Format check with black
        run: |
          pip install black
          black src --check

      # Optional: Deploy Docker image to Azure (or other platforms)
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

      - name: Deploy to Azure Web App (Docker)
        uses: azure/webapps-deploy@v2
        with:
          app-name: flask-app-service-adarsha7
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: '${{ secrets.DOCKER_USERNAME }}/my-app:latest'
